# Generated by Django 2.2 on 2019-04-24 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date:')),
                ('start_shift', models.TimeField(verbose_name='Start time:')),
                ('end_shift', models.TimeField(verbose_name='End Time:')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postion', models.CharField(choices=[('driver', 'Delivery driver'), ('manager', 'Manager'), ('crew', 'Inside Crew'), ('supervisor', 'Open/Close')], max_length=30)),
                ('pay_rate', models.FloatField(verbose_name='Pay Rate:')),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
